### ISSUE TITLE
popup shows "cup_amount"

### ISSUE THREAD

**Issue by mexikoedi** [TTT-2/ttt2-coffeecup#4]
Since the new update (i think) i noticed that the amount of coffee cups is not shown anymore. 
It will display "cup_amount" instead.
Maybe a typo somewhere?
Tested with newest ttt2 base and coffee cup hunt version from the workshop.
Image: https://ibb.co/BLNFTcB

**Comment by TimGoll** [comment]
Fixed. Thanks for letting me know. I always forget that you aren't allowed to use `_` for the variables in param translations
